### ISSUE TITLE
renaming repo suggestion

### ISSUE THREAD

**Issue by Jbarget** [foundersandcoders/handlebars-hapi-intro-workshop#5]
Hey @marisid!

Just thinking, the title of the repo could be worth changing as the workshop is all about `Hapi` + `Handlebars`, as the handlebars morning challenge might be more of an intro to just `handlebars`

**Comment by marisid** [comment]
Hey @Jbarget! Thanks for the suggestion. I believe that this is an intro to Handlebars using a hapi server. The focus of the code along is not learning the hapi framework but rather getting familiar with templating in the same week the cohort learns about hapi. My workshop builds on top of a hapi intro workshop by @msachi.

I think my workshop ties well with your repo, which is a challenge rather than an intro. (all I'm saying is that people should first be introduced to what is templating and how it's often used on the server side before diving straight into a morning challenge as this concept is new at that time in the course for most of them) But I will change the title to *handlebars-hapi-intro-workshop* if you feel this is more clear :smile:

**Comment by Jbarget** [comment]
gotcha! yeh they definitely fit well together :)

Ah it was only a suggestion so only if you agreed

hope you're all good!

**Comment by marisid** [comment]
Yes, all good here @Jbarget 😄 Hope the same for you!
